spring:
  application:
    name: locksmith

  # H2 Database
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  # JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # H2 Console (for development)
  h2:
    console:
      enabled: true

  # Redis (Embedded Redis for development)
  data:
    redis:
      host: localhost
      port: 6379

# Logging
logging:
  level:
    com.ys.locksmith: DEBUG
    org.redisson: INFO